[package]
name = "infra"
version = "0.1.0"
authors = ["Pocket7878 <poketo7878@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
domain = { path = "../domain" }
async-trait = "0.1.24"